name: Ecosystem
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepareEnvironment

      - name: Run lint
        run: pnpm lint

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepareEnvironment

      - name: Run build
        run: pnpm build

  test:
    needs: build
    name: Test Node-${{matrix.node}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["18", "20", "current", "latest"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepareEnvironment
        with:
          node-version: ${{ matrix.node }}

      - name: Run build
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Upload coverage
        if: ${{matrix.node == 'current'}}
        uses: actions/upload-artifact@v4
        with:
          name: Coverage
          path: packages/*/coverage/coverage-summary.json
          retention-days: 1
  coverage:
    name: Coverage
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepareEnvironment

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: Coverage

      - name: Build badges package
        run: pnpm build && pnpm i

      - name: Check badges
        run: pnpm badges:ci
  changesets:
    name: Publish
    needs: [coverage, test, build, lint]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepareEnvironment

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'chore: release package(s)'
          title: 'chore: release package(s)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
