name: Ecosystem
on: [push]
jobs:
  "DisplayAsTree":
    name: 'DisplayAsTree'
    uses: ./.github/workflows/package.yml
    with:
      package: 'displayastree'
  "Language-Flag-Colors":
    name: 'Language-Flag-Colors'
    uses: ./.github/workflows/package.yml
    with:
      package: 'language-flag-colors'
  "Monorepo-Coverage-Badges":
    name: 'Monorepo-Coverage-Badges'
    uses: ./.github/workflows/package.yml
    with:
      package: 'monorepo-coverage-badges'
  coverage:
    name: Coverage
    needs: [DisplayAsTree, Language-Flag-Colors, Monorepo-Coverage-Badges]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepareEnvironment

      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: Coverage

      - name: Build badges package
        run: pnpm build --filter monorepo-coverage-badges && pnpm i

      - name: Check badges
        run: pnpm badges:ci
  changesets:
    name: Publish
    needs: coverage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepareEnvironment

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'chore: release package(s)'
          title: 'chore: release package(s)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}